//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! #import <objc/NSObject.h>

@interface TryCatchHandler //! : NSObject
{
}

+ (void)performSelector:(SEL)arg1 target:(id)arg2;

@end
