//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "Blockhead.h"
#import "MJMath.h"

@class CraftableItemObject, DrawCube, InventoryItem, NSDictionary, NSMutableDictionary;

@interface Action : NSObject
{
  BOOL inProgress;
  BOOL complete;
  BOOL isAI;
  intpair goalTilePos;
  InventoryItem* interactionItem;
  uint16_t interactionItemIndex;
  uint16_t interactionItemSubIndex;
  int goalInteraction;
  int pathType;
  uint64_t interactionObjectID;
  CraftableItemObject* craftableItemObject;
  uint16_t craftCountOrExtraData;
  DrawCube* blockCube;
  InteractionTestResult interactionTestResult;
  NSDictionary* inventoryChange;
  float animationTimer;
}

@property InteractionTestResult interactionTestResult; // @synthesize interactionTestResult;
@property (retain) DrawCube* blockCube; // @synthesize blockCube;
@property uint16_t craftCountOrExtraData; // @synthesize craftCountOrExtraData;
@property (retain) CraftableItemObject* craftableItemObject; // @synthesize craftableItemObject;
@property float animationTimer; // @synthesize animationTimer;
@property BOOL isAI; // @synthesize isAI;
@property int pathType; // @synthesize pathType;  //* PathType
@property int goalInteraction; // @synthesize goalInteraction; //* InteractionType
@property uint64_t interactionObjectID; // @synthesize interactionObjectID;
@property uint16_t interactionItemSubIndex; // @synthesize interactionItemSubIndex;
@property uint16_t interactionItemIndex; // @synthesize interactionItemIndex;
@property (retain) InventoryItem* interactionItem; // @synthesize interactionItem;
@property (retain) NSDictionary* inventoryChange; // @synthesize inventoryChange;
@property intpair goalTilePos; // @synthesize goalTilePos;
@property BOOL complete; // @synthesize complete;
@property BOOL inProgress; // @synthesize inProgress;

- (void)dealloc;
- (NSMutableDictionary*)getSaveDict;
- (Action*)initWithSaveDict:(NSDictionary*)saveDict inventoryItems:(NSArray*)inventoryItems;
- (Action*)initWithGoalPos:(intpair)goalTilePos_
           goalInteraction:(int)goalInteraction_ //* InteractionType
                  pathType:(int)pathType_ //* PathType
           interactionItem:(InventoryItem*)interactionItem_
                 itemIndex:(uint16_t)interactionItemIndex_
              itemSubIndex:(uint16_t)interactionSubItemIndex_
       interactionObjectID:(uint64_t)interactionObjectID_
       craftableItemObject:(CraftableItemObject*)craftableItemObject_
     craftCountOrExtraData:(uint16_t)craftCountOrExtraData_
                      isAI:(BOOL)isAI_
           inventoryChange:(NSDictionary*)inventoryChange_;

@end
