//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "Vector2.h"

@class NSString;

@protocol AddFuelObject <NSObject>
- (Vector2)fuelUIPos;
- (BOOL)canDismissFuelUI;
- (void)addToFuelForItem:(int)arg1;
- (int*)fuelItems;
- (int)fuelItemCount;
- (int)fuelCount;
- (NSString*)title;
@end
