//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

#include "BHNetConstants.h"

@class BHMatch;

@protocol BHMatchDelegate

@optional
- (void)bootAllClientsDueToNoCredit;
- (void)updatePlayerList:(NSArray*)playerListIncoming;
- (void)infoArrived:(NSMutableDictionary*)dict forPlayer:(NSString*)playerID;
- (BOOL)match:(BHMatch*)match shouldReinvitePlayer:(NSString*)playerID;
- (void)match:(BHMatch*)match player:(NSString*)playerID didChangeState:(BHPlayerConnectionState)state;
- (void)match:(BHMatch*)match didReceiveData:(NSData*)data fromPlayer:(NSString*)peerID;
- (void)match:(BHMatch*)match didFailWithError:(NSError*)error;
- (void)match:(BHMatch*)match connectionWithPlayerFailed:(NSString*)playerID withError:(NSError*)error;
@end
