//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! FIXME: Bad macro hack
#ifndef BOOL
#define BOOL bool
#endif

//! #import <objc/NSObject.h>

@class Blockhead, NoiseFunction, World;

@interface BlockheadAI //! : NSObject
{
  Blockhead* blockhead;
  World* world;
  intpair foundTilePos[16];
  char foundTile[16];
  intpair previousActionTiles[32];
  int previousActionCount;
  float inactivityTimer;
  intpair goalDigTile;
  int currentSearchLevel;
  int currentSearchLevelCount;
  BOOL lastFrameHadActions;
  int placableItem;
  int sowableItem;
  float randomInactivityTimer;
  BOOL onlyMoveThisTime;
  NoiseFunction* moveDirectionNoiseFunction;
  float moveDirection;
  float timeElapsed;
  float mustSleepTimer;
}

- (void)noPathToAction;
- (void)update:(float)arg1 isSimulation:(BOOL)arg2;
- (BOOL)testTileAtPos:(intpair)arg1;
- (void)dealloc;
- (id)initWithBlockhead:(id)arg1 world:(id)arg2;

@end
