//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "MJMath.h"

@class Blockhead, NoiseFunction, World;

@interface BlockheadAI : NSObject {
  Blockhead* blockhead;
  World* world;
  intpair foundTilePos[16];
  char foundTile[16];
  intpair previousActionTiles[32];
  int previousActionCount;
  float inactivityTimer;
  intpair goalDigTile;
  int currentSearchLevel;
  int currentSearchLevelCount;
  BOOL lastFrameHadActions;
  int placableItem;
  int sowableItem;
  float randomInactivityTimer;
  BOOL onlyMoveThisTime;
  NoiseFunction* moveDirectionNoiseFunction;
  float moveDirection;
  float timeElapsed;
  float mustSleepTimer;
}

- (void)noPathToAction;
- (void)update:(float)dt isSimulation:(BOOL)isSimulation;
- (BOOL)testTileAtPos:(intpair)pos;
- (BlockheadAI*)initWithBlockhead:(Blockhead*)blockhead_ world:(World*)world_;

@end
