//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CraftableItemObject.h"

@class NSString;

@interface BlockheadCraftableItemObject : CraftableItemObject {
  NSString *name;
  struct BlockheadSkinOptions skinOptions;
}

@property struct BlockheadSkinOptions skinOptions; // @synthesize skinOptions;
@property(retain) NSString *name;                  // @synthesize name;
- (void)dealloc;
- (id)getSaveDict;
- (id)initWithSaveDict:(id)arg1;
- (id)initWithCraftableItem:(struct CraftableItem)arg1
                       name:(id)arg2
                skinOptions:(struct BlockheadSkinOptions)arg3;

@end
