//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NormalPlant.h"

@interface CarrotPlant : NormalPlant
{
}

- (int)npcSpawnType;
- (int)renderImageType;
- (BOOL)isRequiredSoilType:(int)arg1;
- (int)plantType;
- (BOOL)canDieSeason:(int)arg1;
- (BOOL)floweringSeason:(int)arg1;
- (int)minAllowedTemperature;
- (float)foodToRemoveWhenSpawningNPC;
- (int)seedItemType;
- (float)maxAgeBase;
- (int)objectType;

@end

