//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol CraftProgressCraftingObject <NSObject>
- (int)hurryCostForCraftTimeRemaining:(int)arg1 totalCraftTime:(int)arg2;
- (void)hurryCompletion:(int)arg1;
- (void)abortCraft;
- (BOOL)isDoubleHeight;
- (Vector2)floatPos;
- (NSString*)titleForCraftProgressUI;

@optional
- (void)craftProgressUICompleteButtonTapped;
- (BOOL)craftProgressUIRequiresCollectButtonWhenCompleted;
- (void)addToFuelForItem:(int)arg1;
- (int*)fuelTypes;
- (int)fuelCount;
- (int)fuelTypesCount;
- (unsigned short)availableElectricity;
- (BOOL)requiresElectricty;
- (BOOL)requiresFuel;
- (NSString*)upgradeNameForCraftProgressUI;
@end
