//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSOperationQueue, NSString;
@protocol CrystalManagerWatcher;

@interface CrystalManager : NSObject {
  NSOperationQueue* saveQueue;
  int crystalCount;
  NSString* amountString;
  id<CrystalManagerWatcher> countWatcher;
  BOOL needsSave;
}

@property (readonly) NSString* amountString; // @synthesize amountString;
@property (readonly) BOOL needsSave; // @synthesize needsSave;
//! TODO: WHAT ARE YOU MYSTERIOUS ID???
@property id<CrystalManagerWatcher> countWatcher; // @synthesize countWatcher; 

+ (CrystalManager*)instance;
- (NSString*)iCloudServerRejoinID;
- (NSString*)iCloudID;
- (void)modify:(int)count modifyString:(NSString*)modifyString;
- (void)save;
- (void)commitSaveIfNeeded;
- (int)amount;
- (void)loadFromSave;
- (CrystalManager*)init;

@end
