//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! FIXME: Bad macro hack
#ifndef BOOL
#define BOOL bool
#endif

//! #import <objc/NSObject.h>

@class NSString;

@interface DatabaseEnvironment //! : NSObject
{
  struct MDB_env *env;
  struct MDB_txn *bulkTransaction;
  NSString *environmentDirectoryPath;
}

@property(readonly)
    struct MDB_txn *bulkTransaction;     // @synthesize bulkTransaction;
@property(readonly) struct MDB_env *env; // @synthesize env;
- (BOOL)finishBulkTransaction;
- (BOOL)startBulkTransaction;
- (void)dealloc;
- (id)initWithPath:(id)arg1
      maxDatabases:(int)arg2
    maxMapSizeInMB:(unsigned long long)arg3;

@end
