//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TrainCar.h"

#import "ProxyObjectOwner-Protocol.h"

@class Chest, DrawCube, NSString;

@interface FreightCar : TrainCar <ProxyObjectOwner>
{
    DrawCube *platformCube;
    DrawCube *chestCube;
    DrawCube *poleCube;
    Chest *chest;
    BOOL needsChestSave;
}

@property BOOL needsChestSave; // @synthesize needsChestSave;
- (void)setNeedsRemoved:(BOOL)arg1;
- (BOOL)requiresHumanInteraction;
- (BOOL)updateNeedsToBeSent;
- (void)setUpdateNeedsToBeSent:(BOOL)arg1;
- (void)blockheadsLoaded;
- (void)childNeedsSaving:(id)arg1;
- (id)actsAsInteractionObject;
- (BOOL)tapIsWithinBodyRadius:(struct Vector2)arg1;
- (BOOL)blockheadCanRide:(id)arg1 usingItem:(int)arg2;
- (id)actionTitle;
- (int)itemType;
- (void)setTargetVelocity:(struct Vector2)arg1;
- (struct Vector2)cameraPos;
- (struct Vector2)renderPos;
- (void)draw:(float)arg1 projectionMatrix:(union _GLKMatrix4)arg2 modelViewMatrix:(union _GLKMatrix4)arg3 cameraMinXWorld:(int)arg4 cameraMaxXWorld:(int)arg5 cameraMinYWorld:(int)arg6 cameraMaxYWorld:(int)arg7;
- (void)update:(float)arg1 accurateDT:(float)arg2 isSimulation:(BOOL)arg3;
- (void)remoteUpdate:(id)arg1;
- (void)updatePosition:(CDStruct_ffe6b7c1)arg1;
- (void)dealloc;
- (id)updateNetDataForClient:(id)arg1;
- (id)creationNetDataForClient:(id)arg1;
- (id)freeBlockCreationSaveDict;
- (id)getChestSaveDict;
- (id)getSaveDict;
- (id)initWithWorld:(id)arg1 dynamicWorld:(id)arg2 cache:(id)arg3 netData:(id)arg4;
- (id)initWithWorld:(id)arg1 dynamicWorld:(id)arg2 saveDict:(id)arg3 chestSaveDict:(id)arg4 cache:(id)arg5;
- (id)initWithWorld:(id)arg1 dynamicWorld:(id)arg2 atPosition:(CDStruct_ffe6b7c1)arg3 cache:(id)arg4 saveDict:(id)arg5 placedByClient:(id)arg6;
- (int)objectType;
- (void)loadDerivedStuff;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

