//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "Vector2.h"
#import "NSObject-Protocol.h"

@class Blockhead;

@protocol HarmableDynamicObject <NSObject>
- (Vector2)center;
- (BOOL)isVisible;
- (BOOL)willDieIfHitByForce:(int)arg1;
- (void)hitWithForce:(int)arg1 blockhead:(Blockhead *)arg2;
- (BOOL)tapIsWithinBodyRadius:(Vector2)arg1;
@end
