//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! #import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface InventoryItem //! : NSObject
{
    int itemType;
    unsigned short dataA;
    unsigned short dataB;
    NSArray *subItems;
    unsigned char selectedSubItemIndex;
    NSDictionary *dynamicObjectSaveDict;
}

@property(readonly) NSDictionary *dynamicObjectSaveDict; // @synthesize dynamicObjectSaveDict;
@property unsigned short dataB; // @synthesize dataB;
@property unsigned short dataA; // @synthesize dataA;
@property unsigned char selectedSubItemIndex; // @synthesize selectedSubItemIndex;
@property(readonly) NSArray *subItems; // @synthesize subItems;
@property(readonly) int itemType; // @synthesize itemType;
- (id)subItemSlotDataAtIndex:(int)arg1;
- (void)updateSubItemSlot:(id)arg1 atIndex:(int)arg2;
- (id)saveData;
- (id)initWithSaveData:(id)arg1;
- (void)dealloc;
- (id)initWithType:(int)arg1 dataA:(unsigned short)arg2 dataB:(unsigned short)arg3 subItems:(id)arg4 dynamicObjectSaveDict:(id)arg5;

@end

