//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CraftableItemObject.h"

@class NSData;

@interface PaintingCraftableItemObject : CraftableItemObject {
  NSData* imageData;
  NSData* outputImageData;
}

@property (retain) NSData* outputImageData; // @synthesize outputImageData;
@property (retain) NSData* imageData; // @synthesize imageData;
- (id)freeBlockCreationItemSaveDict;
- (void)dealloc;
- (id)getSaveDict;
- (id)initWithSaveDict:(id)arg1;
- (id)initWithCraftableItem:(struct CraftableItem)arg1
                  imageData:(id)arg2
            outputImageData:(id)arg3;

@end
