//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class DynamicObject, NSArray, NSDictionary, NSMutableIndexSet, NSMutableSet,
    World;
@protocol PathUserDynamicObject;

@interface PathCreator : NSObject
{
  World* world;
  DynamicObject<PathUserDynamicObject>* pathUser;
  int goalX;
  int goalY;
  int goalInteraction;
  int pathType;
  NSDictionary* extraData;
  NSMutableIndexSet* openList;
  NSMutableIndexSet* closedList;
  int closestDistance;
  int startIndex;
  BOOL inProgress;
  NSArray* path;
  BOOL hasPath;
  BOOL hasPathToBelowTile;
  BOOL firstTileCheckDone;
  BOOL allowsWaterTiles;
  NSMutableSet* arrayPathsToRelease;
  struct DerivedTileProperties* derivedTilePropertiesArray;
  int derivedTileCount;
  struct map<int, int, std::__1::less<int>,
      std::__1::allocator<std::__1::pair<const int, int>>>
      derivedTileIndices;
  std::vector<intpair> elevatorBlacklist;
}

@property (readonly) NSDictionary* extraData; // @synthesize extraData;
@property BOOL hasPath; // @synthesize hasPath;
@property (readonly) int pathType; // @synthesize pathType;
@property (readonly) int goalInteraction; // @synthesize goalInteraction;
@property (readonly) int goalY; // @synthesize goalY;
@property (readonly) int goalX; // @synthesize goalX;
@property (readonly)
    DynamicObject<PathUserDynamicObject>* pathUser; // @synthesize pathUser;
@property (readonly) BOOL inProgress; // @synthesize inProgress;
@property (readonly) NSArray* path; // @synthesize path;

- (void)abortPath;
- (void)createPathWithDict:(id)arg1;
- (id)calculateFallPath;
- (void)calculatePath;
- (void)updatePath;
- (struct DerivedTileProperties*)tileDerivedPropertiesAtWorldIndex:(int)arg1;
- (void)dealloc;
- (id)initWithWorld:(id)arg1;

@end
