//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! FIXME: Bad macro hack
#ifndef BOOL
#define BOOL bool
#endif

//! #import <objc/NSObject.h>

@class NSArray;

@interface Shader //! : NSObject
{
    unsigned int program;
    NSArray *uniformLocations;
}

@property(readonly) NSArray *uniformLocations; // @synthesize uniformLocations;
@property(readonly) unsigned int program; // @synthesize program;
- (BOOL)validateProgram:(unsigned int)arg1;
- (BOOL)linkProgram:(unsigned int)arg1;
- (BOOL)compileShader:(unsigned int *)arg1 type:(unsigned int)arg2 file:(id)arg3;
- (void)dealloc;
- (id)initWithShaderVertexFile:(id)arg1 fragmentFile:(id)arg2 attributes:(id)arg3 uniforms:(id)arg4;

@end

