//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol SignTextDynamicObject <NSObject>
- (BOOL)requiresSingleLineTextEditing;
- (void)setText:(NSString*)arg1;
- (NSString*)text;
@end
