//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//! #import <objc/NSObject.h>

@class NSString, World;

@interface TipManager //! : NSObject
{
  World* world;
  NSString* currentTipText;
  float timeoutTimer;
  double timeLastSecondBlockheadTipDisplayed;
  Vector tipColor;
  NSString* tutorialTipText;
}

+ (id)instance;
- (id).cxx_construct;
- (void)displaySecondBlockheadTipIfGoodTime;
- (void)updateTipForBlockhead:(id)arg1 severityLevel:(int)arg2;
- (void)setTutorialTipText:(id)arg1;
- (Vector)tipColor;
- (id)currentTip;
- (void)update:(float)arg1;
- (void)displayTip:(id)arg1
              withTimeOut:(float)arg2
    displayEvenIfDisabled:(BOOL)arg3
                 tipColor:(Vector)arg4;
- (void)reset;
- (void)setWorld:(id)arg1;

@end
