//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019
//     19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

@class Blockhead, Database, DatabaseEnvironment, NSDictionary, NSString;

@protocol WorldDelegate
- (void)viewServerWelcomeMessage:(NSString*)arg1
                     customRules:(NSDictionary*)arg2
                       allowEdit:(BOOL)arg3;
- (void)showDieConfirmationForBlockhead:(Blockhead*)arg1;
- (void)pinchZoomToScale:(float)arg1;
- (void)hideChatView;
- (void)showChatUI;
- (void)fileWriteFailed:(NSString*)arg1;
- (void)showBlockheadAvailablePrompt:(int)arg1;
- (BOOL)showDoubleTimePromptIfGoodTime:(NSString*)arg1;
- (void)instructionsButtonTapped;
- (void)achievementsButtonTapped;
- (NSString*)messageForAchivementWithIdentifier:(NSString*)arg1;
- (NSDictionary*)getDefaultGameSaveForWorldWithID:(NSString*)arg1;
- (void)updateiCloudRecentConnectionList;
- (BOOL)secondaryTouchCancelled;
- (void)presentSavedToCameraRollAlert;
- (void)render:(float)arg1;
- (void)startIncentivizedVideo;
- (BOOL)hasRewardedVideoAvailable;
- (DatabaseEnvironment*)appDatabaseEnvironment;
- (Database*)appDatabase;
- (void)iapStarted;
- (void)exitWorld;
- (void)startCameraZoomForTeaserRecord;
- (void)setPaused:(BOOL)arg1;
- (void)connectionToServerOK;
- (void)connectionToServerLostShouldRetry:(BOOL)arg1;
- (void)showWelcomeBackPopupWithMessage:(NSString*)arg1;
@end
