//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GameController, NSDictionary;

@protocol GameControllerDelegate <NSObject>
- (void)clearChat;
- (void)chatMessageRecievedFromGameController:(GameController *)arg1 messageDict:(NSDictionary *)arg2;
- (void)playersChanged;
- (void)loadCompleteForGameController:(GameController *)arg1;
- (void)removeGameController:(GameController *)arg1;
@end

