//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 25 2019 19:18:06).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (searchAdditions)
- (long long)safeCaseInsensitiveCompare:(id)arg1;
- (id)stringByRemovingNonAsciiChars;
- (id)getSubStringBetween:(id)arg1 andEnd:(id)arg2;
@end

